# Generated by Django 5.0.6 on 2024-06-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookborrow',
            name='time_returned',
        ),
    ]
